Removed nonfree,fdkaac,small,openssl. Updated x264,x265. Added nvenc,cuvid
jellyfin/ffmpeg-build pull request #2
Opened 2019-02-20 20:48 UTC by EraYaN

2019-02-20 20:52 UTC, JustAMan approved these changes
LGTM

2019-02-20 20:55 UTC, Bond-009 approved these changes

2019-02-20 21:00 UTC, andrewrabert requested changes
Rejecting until user impact is understood.

2019-02-20 21:09 UTC, EraYaN commented
@nvllsvm What do you mean by "user impact"? I mean the new x264 version adds 10-bit support, and the new version of x265 adds better HDR10/SEI messages support and a whole host of other things.

x265 release notes: https://x265.readthedocs.io/en/default/releasenotes.html

So cuvid/nvenc will only work with nvidia-docker: https://github.com/NVIDIA/nvidia-docker
So for most users not using mainsteam LTS versions of linux that will not be an option, since nvidia only releases these on distributions that support CUDA.

As for openssl, right now it will not support https (sources). For that we would need to add `--enable-gnutls` to the build.

fdkaac is just an impossibility so user impact does not matter, native aac is good enough.

2019-02-21 03:49 UTC, nvllsvm commented
Yup - an explanation like that is what I was looking for. Include it in the description or better yet commit next time please!

2019-02-21 03:49 UTC, andrewrabert approved these changes

2019-02-21 03:49 UTC, merged